# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/workspace/cs5700_hw5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/workspace/cs5700_hw5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/cs5700_hw5/CMakeFiles /home/ubuntu/workspace/cs5700_hw5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/cs5700_hw5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppShellHW5

# Build rule for target.
cppShellHW5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppShellHW5
.PHONY : cppShellHW5

# fast build rule for target.
cppShellHW5/fast:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/build
.PHONY : cppShellHW5/fast

# target to build an object file
CdCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/CdCommand.o
.PHONY : CdCommand.o

# target to preprocess a source file
CdCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/CdCommand.i
.PHONY : CdCommand.i

# target to generate assembly for a file
CdCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/CdCommand.s
.PHONY : CdCommand.s

# target to build an object file
Command.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/Command.o
.PHONY : Command.o

# target to preprocess a source file
Command.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/Command.i
.PHONY : Command.i

# target to generate assembly for a file
Command.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/Command.s
.PHONY : Command.s

# target to build an object file
CommandFactory.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/CommandFactory.o
.PHONY : CommandFactory.o

# target to preprocess a source file
CommandFactory.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/CommandFactory.i
.PHONY : CommandFactory.i

# target to generate assembly for a file
CommandFactory.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/CommandFactory.s
.PHONY : CommandFactory.s

# target to build an object file
ExitCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/ExitCommand.o
.PHONY : ExitCommand.o

# target to preprocess a source file
ExitCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/ExitCommand.i
.PHONY : ExitCommand.i

# target to generate assembly for a file
ExitCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/ExitCommand.s
.PHONY : ExitCommand.s

# target to build an object file
HistoryCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/HistoryCommand.o
.PHONY : HistoryCommand.o

# target to preprocess a source file
HistoryCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/HistoryCommand.i
.PHONY : HistoryCommand.i

# target to generate assembly for a file
HistoryCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/HistoryCommand.s
.PHONY : HistoryCommand.s

# target to build an object file
MessageCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/MessageCommand.o
.PHONY : MessageCommand.o

# target to preprocess a source file
MessageCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/MessageCommand.i
.PHONY : MessageCommand.i

# target to generate assembly for a file
MessageCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/MessageCommand.s
.PHONY : MessageCommand.s

# target to build an object file
PTimeCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/PTimeCommand.o
.PHONY : PTimeCommand.o

# target to preprocess a source file
PTimeCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/PTimeCommand.i
.PHONY : PTimeCommand.i

# target to generate assembly for a file
PTimeCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/PTimeCommand.s
.PHONY : PTimeCommand.s

# target to build an object file
PipeCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/PipeCommand.o
.PHONY : PipeCommand.o

# target to preprocess a source file
PipeCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/PipeCommand.i
.PHONY : PipeCommand.i

# target to generate assembly for a file
PipeCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/PipeCommand.s
.PHONY : PipeCommand.s

# target to build an object file
Shell.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/Shell.o
.PHONY : Shell.o

# target to preprocess a source file
Shell.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/Shell.i
.PHONY : Shell.i

# target to generate assembly for a file
Shell.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/Shell.s
.PHONY : Shell.s

# target to build an object file
SystemCommand.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/SystemCommand.o
.PHONY : SystemCommand.o

# target to preprocess a source file
SystemCommand.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/SystemCommand.i
.PHONY : SystemCommand.i

# target to generate assembly for a file
SystemCommand.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/SystemCommand.s
.PHONY : SystemCommand.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/cppShellHW5.dir/build.make CMakeFiles/cppShellHW5.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cppShellHW5"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CdCommand.o"
	@echo "... CdCommand.i"
	@echo "... CdCommand.s"
	@echo "... Command.o"
	@echo "... Command.i"
	@echo "... Command.s"
	@echo "... CommandFactory.o"
	@echo "... CommandFactory.i"
	@echo "... CommandFactory.s"
	@echo "... ExitCommand.o"
	@echo "... ExitCommand.i"
	@echo "... ExitCommand.s"
	@echo "... HistoryCommand.o"
	@echo "... HistoryCommand.i"
	@echo "... HistoryCommand.s"
	@echo "... MessageCommand.o"
	@echo "... MessageCommand.i"
	@echo "... MessageCommand.s"
	@echo "... PTimeCommand.o"
	@echo "... PTimeCommand.i"
	@echo "... PTimeCommand.s"
	@echo "... PipeCommand.o"
	@echo "... PipeCommand.i"
	@echo "... PipeCommand.s"
	@echo "... Shell.o"
	@echo "... Shell.i"
	@echo "... Shell.s"
	@echo "... SystemCommand.o"
	@echo "... SystemCommand.i"
	@echo "... SystemCommand.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

